//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Otdel
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Вид кредита.
    /// </summary>
    // *** Start programmer edit section *** (ВидКредита CustomAttributes)

    // *** End programmer edit section *** (ВидКредита CustomAttributes)
    public enum ВидКредита
    {
        
        // *** Start programmer edit section *** (ВидКредита.Ипотечный CustomAttributes)

        // *** End programmer edit section *** (ВидКредита.Ипотечный CustomAttributes)
        Ипотечный,
        
        // *** Start programmer edit section *** (ВидКредита.Потребительский CustomAttributes)

        // *** End programmer edit section *** (ВидКредита.Потребительский CustomAttributes)
        Потребительский,
        
        // *** Start programmer edit section *** (ВидКредита.Коммерческий CustomAttributes)

        // *** End programmer edit section *** (ВидКредита.Коммерческий CustomAttributes)
        Коммерческий,
        
        // *** Start programmer edit section *** (ВидКредита.Международный CustomAttributes)

        // *** End programmer edit section *** (ВидКредита.Международный CustomAttributes)
        Международный,
        
        // *** Start programmer edit section *** (ВидКредита.Государственный CustomAttributes)

        // *** End programmer edit section *** (ВидКредита.Государственный CustomAttributes)
        Государственный,
        
        // *** Start programmer edit section *** (ВидКредита.Автокредит CustomAttributes)

        // *** End programmer edit section *** (ВидКредита.Автокредит CustomAttributes)
        Автокредит,
    }
}
