//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Otdel
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Клиенты.
    /// </summary>
    // *** Start programmer edit section *** (Клиенты CustomAttributes)

    // *** End programmer edit section *** (Клиенты CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КлиентыE", new string[] {
            "ФИО as \'ФИО\'",
            "ИНН as \'ИНН\'",
            "КПП as \'КПП\'",
            "Телефон as \'Телефон\'",
            "МестоРаботы as \'Место работы\'",
            "ЮрАдрес as \'Юр адрес\'",
            "ФактАдрес as \'Факт адрес\'",
            "СтажРаботы as \'Стаж работы\'",
            "НомКрДог as \'Ном кр дог\'",
            "РасчСчет as \'Расч счет\'",
            "ЗаклКрДог as \'Закл кр дог\'",
            "ЗаклКрДог.ЦельКр as \'Цель кр\'",
            "ПроверкаКрКл as \'Проверка кр кл\'",
            "ПроверкаКрКл.НаличЗалога as \'Налич залога\'",
            "ПогашКр as \'Погаш кр\'",
            "ПогашКр.Дата as \'Дата\'"}, Hidden=new string[] {
            "ЗаклКрДог.ЦельКр",
            "ПроверкаКрКл.НаличЗалога",
            "ПогашКр.Дата"})]
    [MasterViewDefineAttribute("КлиентыE", "ЗаклКрДог", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ЦельКр")]
    [MasterViewDefineAttribute("КлиентыE", "ПроверкаКрКл", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НаличЗалога")]
    [MasterViewDefineAttribute("КлиентыE", "ПогашКр", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Дата")]
    [View("КлиентыL", new string[] {
            "ФИО as \'ФИО\'",
            "ИНН as \'ИНН\'",
            "КПП as \'КПП\'",
            "Телефон as \'Телефон\'",
            "МестоРаботы as \'Место работы\'",
            "ЮрАдрес as \'Юр адрес\'",
            "ФактАдрес as \'Факт адрес\'",
            "СтажРаботы as \'Стаж работы\'",
            "НомКрДог as \'Ном кр дог\'",
            "РасчСчет as \'Расч счет\'"})]
    public class Клиенты : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИО;
        
        private int fИНН;
        
        private int fКПП;
        
        private int fТелефон;
        
        private string fМестоРаботы;
        
        private string fЮрАдрес;
        
        private string fФактАдрес;
        
        private int fСтажРаботы;
        
        private int fНомКрДог;
        
        private int fРасчСчет;
        
        private IIS.Otdel.ЗаклКрДог fЗаклКрДог;
        
        private IIS.Otdel.ПроверкаКрКл fПроверкаКрКл;
        
        private IIS.Otdel.ПогашКр fПогашКр;
        
        // *** Start programmer edit section *** (Клиенты CustomMembers)

        // *** End programmer edit section *** (Клиенты CustomMembers)

        
        /// <summary>
        /// ИНН.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.ИНН CustomAttributes)

        // *** End programmer edit section *** (Клиенты.ИНН CustomAttributes)
        public virtual int ИНН
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.ИНН Get start)

                // *** End programmer edit section *** (Клиенты.ИНН Get start)
                int result = this.fИНН;
                // *** Start programmer edit section *** (Клиенты.ИНН Get end)

                // *** End programmer edit section *** (Клиенты.ИНН Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.ИНН Set start)

                // *** End programmer edit section *** (Клиенты.ИНН Set start)
                this.fИНН = value;
                // *** Start programmer edit section *** (Клиенты.ИНН Set end)

                // *** End programmer edit section *** (Клиенты.ИНН Set end)
            }
        }
        
        /// <summary>
        /// КПП.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.КПП CustomAttributes)

        // *** End programmer edit section *** (Клиенты.КПП CustomAttributes)
        public virtual int КПП
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.КПП Get start)

                // *** End programmer edit section *** (Клиенты.КПП Get start)
                int result = this.fКПП;
                // *** Start programmer edit section *** (Клиенты.КПП Get end)

                // *** End programmer edit section *** (Клиенты.КПП Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.КПП Set start)

                // *** End programmer edit section *** (Клиенты.КПП Set start)
                this.fКПП = value;
                // *** Start programmer edit section *** (Клиенты.КПП Set end)

                // *** End programmer edit section *** (Клиенты.КПП Set end)
            }
        }
        
        /// <summary>
        /// МестоРаботы.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.МестоРаботы CustomAttributes)

        // *** End programmer edit section *** (Клиенты.МестоРаботы CustomAttributes)
        [StrLen(255)]
        public virtual string МестоРаботы
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.МестоРаботы Get start)

                // *** End programmer edit section *** (Клиенты.МестоРаботы Get start)
                string result = this.fМестоРаботы;
                // *** Start programmer edit section *** (Клиенты.МестоРаботы Get end)

                // *** End programmer edit section *** (Клиенты.МестоРаботы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.МестоРаботы Set start)

                // *** End programmer edit section *** (Клиенты.МестоРаботы Set start)
                this.fМестоРаботы = value;
                // *** Start programmer edit section *** (Клиенты.МестоРаботы Set end)

                // *** End programmer edit section *** (Клиенты.МестоРаботы Set end)
            }
        }
        
        /// <summary>
        /// НомКрДог.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.НомКрДог CustomAttributes)

        // *** End programmer edit section *** (Клиенты.НомКрДог CustomAttributes)
        public virtual int НомКрДог
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.НомКрДог Get start)

                // *** End programmer edit section *** (Клиенты.НомКрДог Get start)
                int result = this.fНомКрДог;
                // *** Start programmer edit section *** (Клиенты.НомКрДог Get end)

                // *** End programmer edit section *** (Клиенты.НомКрДог Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.НомКрДог Set start)

                // *** End programmer edit section *** (Клиенты.НомКрДог Set start)
                this.fНомКрДог = value;
                // *** Start programmer edit section *** (Клиенты.НомКрДог Set end)

                // *** End programmer edit section *** (Клиенты.НомКрДог Set end)
            }
        }
        
        /// <summary>
        /// РасчСчет.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.РасчСчет CustomAttributes)

        // *** End programmer edit section *** (Клиенты.РасчСчет CustomAttributes)
        public virtual int РасчСчет
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.РасчСчет Get start)

                // *** End programmer edit section *** (Клиенты.РасчСчет Get start)
                int result = this.fРасчСчет;
                // *** Start programmer edit section *** (Клиенты.РасчСчет Get end)

                // *** End programmer edit section *** (Клиенты.РасчСчет Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.РасчСчет Set start)

                // *** End programmer edit section *** (Клиенты.РасчСчет Set start)
                this.fРасчСчет = value;
                // *** Start programmer edit section *** (Клиенты.РасчСчет Set end)

                // *** End programmer edit section *** (Клиенты.РасчСчет Set end)
            }
        }
        
        /// <summary>
        /// СтажРаботы.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.СтажРаботы CustomAttributes)

        // *** End programmer edit section *** (Клиенты.СтажРаботы CustomAttributes)
        public virtual int СтажРаботы
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.СтажРаботы Get start)

                // *** End programmer edit section *** (Клиенты.СтажРаботы Get start)
                int result = this.fСтажРаботы;
                // *** Start programmer edit section *** (Клиенты.СтажРаботы Get end)

                // *** End programmer edit section *** (Клиенты.СтажРаботы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.СтажРаботы Set start)

                // *** End programmer edit section *** (Клиенты.СтажРаботы Set start)
                this.fСтажРаботы = value;
                // *** Start programmer edit section *** (Клиенты.СтажРаботы Set end)

                // *** End programmer edit section *** (Клиенты.СтажРаботы Set end)
            }
        }
        
        /// <summary>
        /// Телефон.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.Телефон CustomAttributes)

        // *** End programmer edit section *** (Клиенты.Телефон CustomAttributes)
        public virtual int Телефон
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.Телефон Get start)

                // *** End programmer edit section *** (Клиенты.Телефон Get start)
                int result = this.fТелефон;
                // *** Start programmer edit section *** (Клиенты.Телефон Get end)

                // *** End programmer edit section *** (Клиенты.Телефон Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.Телефон Set start)

                // *** End programmer edit section *** (Клиенты.Телефон Set start)
                this.fТелефон = value;
                // *** Start programmer edit section *** (Клиенты.Телефон Set end)

                // *** End programmer edit section *** (Клиенты.Телефон Set end)
            }
        }
        
        /// <summary>
        /// ФактАдрес.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.ФактАдрес CustomAttributes)

        // *** End programmer edit section *** (Клиенты.ФактАдрес CustomAttributes)
        [StrLen(255)]
        public virtual string ФактАдрес
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.ФактАдрес Get start)

                // *** End programmer edit section *** (Клиенты.ФактАдрес Get start)
                string result = this.fФактАдрес;
                // *** Start programmer edit section *** (Клиенты.ФактАдрес Get end)

                // *** End programmer edit section *** (Клиенты.ФактАдрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.ФактАдрес Set start)

                // *** End programmer edit section *** (Клиенты.ФактАдрес Set start)
                this.fФактАдрес = value;
                // *** Start programmer edit section *** (Клиенты.ФактАдрес Set end)

                // *** End programmer edit section *** (Клиенты.ФактАдрес Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.ФИО CustomAttributes)

        // *** End programmer edit section *** (Клиенты.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.ФИО Get start)

                // *** End programmer edit section *** (Клиенты.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Клиенты.ФИО Get end)

                // *** End programmer edit section *** (Клиенты.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.ФИО Set start)

                // *** End programmer edit section *** (Клиенты.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Клиенты.ФИО Set end)

                // *** End programmer edit section *** (Клиенты.ФИО Set end)
            }
        }
        
        /// <summary>
        /// ЮрАдрес.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.ЮрАдрес CustomAttributes)

        // *** End programmer edit section *** (Клиенты.ЮрАдрес CustomAttributes)
        [StrLen(255)]
        public virtual string ЮрАдрес
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.ЮрАдрес Get start)

                // *** End programmer edit section *** (Клиенты.ЮрАдрес Get start)
                string result = this.fЮрАдрес;
                // *** Start programmer edit section *** (Клиенты.ЮрАдрес Get end)

                // *** End programmer edit section *** (Клиенты.ЮрАдрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.ЮрАдрес Set start)

                // *** End programmer edit section *** (Клиенты.ЮрАдрес Set start)
                this.fЮрАдрес = value;
                // *** Start programmer edit section *** (Клиенты.ЮрАдрес Set end)

                // *** End programmer edit section *** (Клиенты.ЮрАдрес Set end)
            }
        }
        
        /// <summary>
        /// Клиенты.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.ЗаклКрДог CustomAttributes)

        // *** End programmer edit section *** (Клиенты.ЗаклКрДог CustomAttributes)
        [PropertyStorage(new string[] {
                "ЗаклКрДог"})]
        [NotNull()]
        public virtual IIS.Otdel.ЗаклКрДог ЗаклКрДог
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.ЗаклКрДог Get start)

                // *** End programmer edit section *** (Клиенты.ЗаклКрДог Get start)
                IIS.Otdel.ЗаклКрДог result = this.fЗаклКрДог;
                // *** Start programmer edit section *** (Клиенты.ЗаклКрДог Get end)

                // *** End programmer edit section *** (Клиенты.ЗаклКрДог Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.ЗаклКрДог Set start)

                // *** End programmer edit section *** (Клиенты.ЗаклКрДог Set start)
                this.fЗаклКрДог = value;
                // *** Start programmer edit section *** (Клиенты.ЗаклКрДог Set end)

                // *** End programmer edit section *** (Клиенты.ЗаклКрДог Set end)
            }
        }
        
        /// <summary>
        /// Клиенты.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.ПогашКр CustomAttributes)

        // *** End programmer edit section *** (Клиенты.ПогашКр CustomAttributes)
        [PropertyStorage(new string[] {
                "ПогашКр"})]
        [NotNull()]
        public virtual IIS.Otdel.ПогашКр ПогашКр
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.ПогашКр Get start)

                // *** End programmer edit section *** (Клиенты.ПогашКр Get start)
                IIS.Otdel.ПогашКр result = this.fПогашКр;
                // *** Start programmer edit section *** (Клиенты.ПогашКр Get end)

                // *** End programmer edit section *** (Клиенты.ПогашКр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.ПогашКр Set start)

                // *** End programmer edit section *** (Клиенты.ПогашКр Set start)
                this.fПогашКр = value;
                // *** Start programmer edit section *** (Клиенты.ПогашКр Set end)

                // *** End programmer edit section *** (Клиенты.ПогашКр Set end)
            }
        }
        
        /// <summary>
        /// Клиенты.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.ПроверкаКрКл CustomAttributes)

        // *** End programmer edit section *** (Клиенты.ПроверкаКрКл CustomAttributes)
        [PropertyStorage(new string[] {
                "ПроверкаКрКл"})]
        [NotNull()]
        public virtual IIS.Otdel.ПроверкаКрКл ПроверкаКрКл
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.ПроверкаКрКл Get start)

                // *** End programmer edit section *** (Клиенты.ПроверкаКрКл Get start)
                IIS.Otdel.ПроверкаКрКл result = this.fПроверкаКрКл;
                // *** Start programmer edit section *** (Клиенты.ПроверкаКрКл Get end)

                // *** End programmer edit section *** (Клиенты.ПроверкаКрКл Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.ПроверкаКрКл Set start)

                // *** End programmer edit section *** (Клиенты.ПроверкаКрКл Set start)
                this.fПроверкаКрКл = value;
                // *** Start programmer edit section *** (Клиенты.ПроверкаКрКл Set end)

                // *** End programmer edit section *** (Клиенты.ПроверкаКрКл Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КлиентыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентыE", typeof(IIS.Otdel.Клиенты));
                }
            }
            
            /// <summary>
            /// "КлиентыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентыL", typeof(IIS.Otdel.Клиенты));
                }
            }
        }
    }
}
