//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Otdel
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Отдел кр.
    /// </summary>
    // *** Start programmer edit section *** (ОтделКр CustomAttributes)

    // *** End programmer edit section *** (ОтделКр CustomAttributes)
    [AutoAltered()]
    [Caption("Отдел кр")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОтделКрE", new string[0])]
    [View("ОтделКрL", new string[0])]
    public class ОтделКр : ICSSoft.STORMNET.DataObject
    {
        
        // *** Start programmer edit section *** (ОтделКр CustomMembers)

        // *** End programmer edit section *** (ОтделКр CustomMembers)

        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОтделКрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтделКрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтделКрE", typeof(IIS.Otdel.ОтделКр));
                }
            }
            
            /// <summary>
            /// "ОтделКрL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтделКрL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтделКрL", typeof(IIS.Otdel.ОтделКр));
                }
            }
        }
    }
}
