//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Otdel
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Погаш кр.
    /// </summary>
    // *** Start programmer edit section *** (ПогашКр CustomAttributes)

    // *** End programmer edit section *** (ПогашКр CustomAttributes)
    [AutoAltered()]
    [Caption("Погаш кр")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПогашКрE", new string[] {
            "Дата as \'Дата\'",
            "ВидПогашКр as \'Вид погаш кр\'",
            "СуммаПогашКр as \'Сумма погаш кр\'",
            "ЗаклКрДог as \'Закл кр дог\'",
            "ЗаклКрДог.ЦельКр as \'Цель кр\'",
            "Организация as \'Организация\'",
            "Организация.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "ЗаклКрДог.ЦельКр",
            "Организация.Наименование"})]
    [MasterViewDefineAttribute("ПогашКрE", "ЗаклКрДог", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ЦельКр")]
    [MasterViewDefineAttribute("ПогашКрE", "Организация", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("ПогашКрL", new string[] {
            "Дата as \'Дата\'",
            "ВидПогашКр as \'Вид погаш кр\'",
            "СуммаПогашКр as \'Сумма погаш кр\'",
            "ЗаклКрДог.ЦельКр as \'Цель кр\'",
            "Организация.Наименование as \'Наименование\'"})]
    public class ПогашКр : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private IIS.Otdel.ВидПогашКр fВидПогашКр;
        
        private int fСуммаПогашКр;
        
        private IIS.Otdel.ЗаклКрДог fЗаклКрДог;
        
        private IIS.Otdel.Организация fОрганизация;
        
        // *** Start programmer edit section *** (ПогашКр CustomMembers)

        // *** End programmer edit section *** (ПогашКр CustomMembers)

        
        /// <summary>
        /// ВидПогашКр.
        /// </summary>
        // *** Start programmer edit section *** (ПогашКр.ВидПогашКр CustomAttributes)

        // *** End programmer edit section *** (ПогашКр.ВидПогашКр CustomAttributes)
        public virtual IIS.Otdel.ВидПогашКр ВидПогашКр
        {
            get
            {
                // *** Start programmer edit section *** (ПогашКр.ВидПогашКр Get start)

                // *** End programmer edit section *** (ПогашКр.ВидПогашКр Get start)
                IIS.Otdel.ВидПогашКр result = this.fВидПогашКр;
                // *** Start programmer edit section *** (ПогашКр.ВидПогашКр Get end)

                // *** End programmer edit section *** (ПогашКр.ВидПогашКр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПогашКр.ВидПогашКр Set start)

                // *** End programmer edit section *** (ПогашКр.ВидПогашКр Set start)
                this.fВидПогашКр = value;
                // *** Start programmer edit section *** (ПогашКр.ВидПогашКр Set end)

                // *** End programmer edit section *** (ПогашКр.ВидПогашКр Set end)
            }
        }
        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ПогашКр.Дата CustomAttributes)

        // *** End programmer edit section *** (ПогашКр.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ПогашКр.Дата Get start)

                // *** End programmer edit section *** (ПогашКр.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ПогашКр.Дата Get end)

                // *** End programmer edit section *** (ПогашКр.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПогашКр.Дата Set start)

                // *** End programmer edit section *** (ПогашКр.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ПогашКр.Дата Set end)

                // *** End programmer edit section *** (ПогашКр.Дата Set end)
            }
        }
        
        /// <summary>
        /// СуммаПогашКр.
        /// </summary>
        // *** Start programmer edit section *** (ПогашКр.СуммаПогашКр CustomAttributes)

        // *** End programmer edit section *** (ПогашКр.СуммаПогашКр CustomAttributes)
        public virtual int СуммаПогашКр
        {
            get
            {
                // *** Start programmer edit section *** (ПогашКр.СуммаПогашКр Get start)

                // *** End programmer edit section *** (ПогашКр.СуммаПогашКр Get start)
                int result = this.fСуммаПогашКр;
                // *** Start programmer edit section *** (ПогашКр.СуммаПогашКр Get end)

                // *** End programmer edit section *** (ПогашКр.СуммаПогашКр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПогашКр.СуммаПогашКр Set start)

                // *** End programmer edit section *** (ПогашКр.СуммаПогашКр Set start)
                this.fСуммаПогашКр = value;
                // *** Start programmer edit section *** (ПогашКр.СуммаПогашКр Set end)

                // *** End programmer edit section *** (ПогашКр.СуммаПогашКр Set end)
            }
        }
        
        /// <summary>
        /// Погаш кр.
        /// </summary>
        // *** Start programmer edit section *** (ПогашКр.ЗаклКрДог CustomAttributes)

        // *** End programmer edit section *** (ПогашКр.ЗаклКрДог CustomAttributes)
        [PropertyStorage(new string[] {
                "ЗаклКрДог"})]
        [NotNull()]
        public virtual IIS.Otdel.ЗаклКрДог ЗаклКрДог
        {
            get
            {
                // *** Start programmer edit section *** (ПогашКр.ЗаклКрДог Get start)

                // *** End programmer edit section *** (ПогашКр.ЗаклКрДог Get start)
                IIS.Otdel.ЗаклКрДог result = this.fЗаклКрДог;
                // *** Start programmer edit section *** (ПогашКр.ЗаклКрДог Get end)

                // *** End programmer edit section *** (ПогашКр.ЗаклКрДог Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПогашКр.ЗаклКрДог Set start)

                // *** End programmer edit section *** (ПогашКр.ЗаклКрДог Set start)
                this.fЗаклКрДог = value;
                // *** Start programmer edit section *** (ПогашКр.ЗаклКрДог Set end)

                // *** End programmer edit section *** (ПогашКр.ЗаклКрДог Set end)
            }
        }
        
        /// <summary>
        /// Погаш кр.
        /// </summary>
        // *** Start programmer edit section *** (ПогашКр.Организация CustomAttributes)

        // *** End programmer edit section *** (ПогашКр.Организация CustomAttributes)
        [PropertyStorage(new string[] {
                "Организация"})]
        [NotNull()]
        public virtual IIS.Otdel.Организация Организация
        {
            get
            {
                // *** Start programmer edit section *** (ПогашКр.Организация Get start)

                // *** End programmer edit section *** (ПогашКр.Организация Get start)
                IIS.Otdel.Организация result = this.fОрганизация;
                // *** Start programmer edit section *** (ПогашКр.Организация Get end)

                // *** End programmer edit section *** (ПогашКр.Организация Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПогашКр.Организация Set start)

                // *** End programmer edit section *** (ПогашКр.Организация Set start)
                this.fОрганизация = value;
                // *** Start programmer edit section *** (ПогашКр.Организация Set end)

                // *** End programmer edit section *** (ПогашКр.Организация Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПогашКрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПогашКрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПогашКрE", typeof(IIS.Otdel.ПогашКр));
                }
            }
            
            /// <summary>
            /// "ПогашКрL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПогашКрL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПогашКрL", typeof(IIS.Otdel.ПогашКр));
                }
            }
        }
    }
}
