//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Otdel
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Проверка кр кл.
    /// </summary>
    // *** Start programmer edit section *** (ПроверкаКрКл CustomAttributes)

    // *** End programmer edit section *** (ПроверкаКрКл CustomAttributes)
    [AutoAltered()]
    [Caption("Проверка кр кл")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПроверкаКрКлE", new string[] {
            "Дата as \'Дата\'",
            "ДоходыВМес as \'Доходы в мес\'",
            "СуммаЕжПлЗаКр as \'Сумма еж пл за кр\'",
            "НаличЗалога as \'Налич залога\'",
            "НаличиеПоручит as \'Наличие поручит\'",
            "ОдобрениеКр as \'Одобрение кр\'",
            "Организация as \'Организация\'",
            "Организация.Наименование as \'Наименование\'",
            "ЗаклКрДог as \'Закл кр дог\'",
            "ЗаклКрДог.ЦельКр as \'Цель кр\'"}, Hidden=new string[] {
            "Организация.Наименование",
            "ЗаклКрДог.ЦельКр"})]
    [MasterViewDefineAttribute("ПроверкаКрКлE", "Организация", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("ПроверкаКрКлE", "ЗаклКрДог", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ЦельКр")]
    [View("ПроверкаКрКлL", new string[] {
            "Дата as \'Дата\'",
            "ДоходыВМес as \'Доходы в мес\'",
            "СуммаЕжПлЗаКр as \'Сумма еж пл за кр\'",
            "НаличЗалога as \'Налич залога\'",
            "НаличиеПоручит as \'Наличие поручит\'",
            "ОдобрениеКр as \'Одобрение кр\'",
            "Организация.Наименование as \'Наименование\'",
            "ЗаклКрДог.ЦельКр as \'Цель кр\'"})]
    public class ПроверкаКрКл : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private int fДоходыВМес;
        
        private int fСуммаЕжПлЗаКр;
        
        private string fНаличЗалога;
        
        private string fНаличиеПоручит;
        
        private bool fОдобрениеКр;
        
        private IIS.Otdel.Организация fОрганизация;
        
        private IIS.Otdel.ЗаклКрДог fЗаклКрДог;
        
        // *** Start programmer edit section *** (ПроверкаКрКл CustomMembers)

        // *** End programmer edit section *** (ПроверкаКрКл CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ПроверкаКрКл.Дата CustomAttributes)

        // *** End programmer edit section *** (ПроверкаКрКл.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ПроверкаКрКл.Дата Get start)

                // *** End programmer edit section *** (ПроверкаКрКл.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ПроверкаКрКл.Дата Get end)

                // *** End programmer edit section *** (ПроверкаКрКл.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПроверкаКрКл.Дата Set start)

                // *** End programmer edit section *** (ПроверкаКрКл.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ПроверкаКрКл.Дата Set end)

                // *** End programmer edit section *** (ПроверкаКрКл.Дата Set end)
            }
        }
        
        /// <summary>
        /// ДоходыВМес.
        /// </summary>
        // *** Start programmer edit section *** (ПроверкаКрКл.ДоходыВМес CustomAttributes)

        // *** End programmer edit section *** (ПроверкаКрКл.ДоходыВМес CustomAttributes)
        public virtual int ДоходыВМес
        {
            get
            {
                // *** Start programmer edit section *** (ПроверкаКрКл.ДоходыВМес Get start)

                // *** End programmer edit section *** (ПроверкаКрКл.ДоходыВМес Get start)
                int result = this.fДоходыВМес;
                // *** Start programmer edit section *** (ПроверкаКрКл.ДоходыВМес Get end)

                // *** End programmer edit section *** (ПроверкаКрКл.ДоходыВМес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПроверкаКрКл.ДоходыВМес Set start)

                // *** End programmer edit section *** (ПроверкаКрКл.ДоходыВМес Set start)
                this.fДоходыВМес = value;
                // *** Start programmer edit section *** (ПроверкаКрКл.ДоходыВМес Set end)

                // *** End programmer edit section *** (ПроверкаКрКл.ДоходыВМес Set end)
            }
        }
        
        /// <summary>
        /// НаличЗалога.
        /// </summary>
        // *** Start programmer edit section *** (ПроверкаКрКл.НаличЗалога CustomAttributes)

        // *** End programmer edit section *** (ПроверкаКрКл.НаличЗалога CustomAttributes)
        [StrLen(255)]
        public virtual string НаличЗалога
        {
            get
            {
                // *** Start programmer edit section *** (ПроверкаКрКл.НаличЗалога Get start)

                // *** End programmer edit section *** (ПроверкаКрКл.НаличЗалога Get start)
                string result = this.fНаличЗалога;
                // *** Start programmer edit section *** (ПроверкаКрКл.НаличЗалога Get end)

                // *** End programmer edit section *** (ПроверкаКрКл.НаличЗалога Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПроверкаКрКл.НаличЗалога Set start)

                // *** End programmer edit section *** (ПроверкаКрКл.НаличЗалога Set start)
                this.fНаличЗалога = value;
                // *** Start programmer edit section *** (ПроверкаКрКл.НаличЗалога Set end)

                // *** End programmer edit section *** (ПроверкаКрКл.НаличЗалога Set end)
            }
        }
        
        /// <summary>
        /// НаличиеПоручит.
        /// </summary>
        // *** Start programmer edit section *** (ПроверкаКрКл.НаличиеПоручит CustomAttributes)

        // *** End programmer edit section *** (ПроверкаКрКл.НаличиеПоручит CustomAttributes)
        [StrLen(255)]
        public virtual string НаличиеПоручит
        {
            get
            {
                // *** Start programmer edit section *** (ПроверкаКрКл.НаличиеПоручит Get start)

                // *** End programmer edit section *** (ПроверкаКрКл.НаличиеПоручит Get start)
                string result = this.fНаличиеПоручит;
                // *** Start programmer edit section *** (ПроверкаКрКл.НаличиеПоручит Get end)

                // *** End programmer edit section *** (ПроверкаКрКл.НаличиеПоручит Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПроверкаКрКл.НаличиеПоручит Set start)

                // *** End programmer edit section *** (ПроверкаКрКл.НаличиеПоручит Set start)
                this.fНаличиеПоручит = value;
                // *** Start programmer edit section *** (ПроверкаКрКл.НаличиеПоручит Set end)

                // *** End programmer edit section *** (ПроверкаКрКл.НаличиеПоручит Set end)
            }
        }
        
        /// <summary>
        /// ОдобрениеКр.
        /// </summary>
        // *** Start programmer edit section *** (ПроверкаКрКл.ОдобрениеКр CustomAttributes)

        // *** End programmer edit section *** (ПроверкаКрКл.ОдобрениеКр CustomAttributes)
        public virtual bool ОдобрениеКр
        {
            get
            {
                // *** Start programmer edit section *** (ПроверкаКрКл.ОдобрениеКр Get start)

                // *** End programmer edit section *** (ПроверкаКрКл.ОдобрениеКр Get start)
                bool result = this.fОдобрениеКр;
                // *** Start programmer edit section *** (ПроверкаКрКл.ОдобрениеКр Get end)

                // *** End programmer edit section *** (ПроверкаКрКл.ОдобрениеКр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПроверкаКрКл.ОдобрениеКр Set start)

                // *** End programmer edit section *** (ПроверкаКрКл.ОдобрениеКр Set start)
                this.fОдобрениеКр = value;
                // *** Start programmer edit section *** (ПроверкаКрКл.ОдобрениеКр Set end)

                // *** End programmer edit section *** (ПроверкаКрКл.ОдобрениеКр Set end)
            }
        }
        
        /// <summary>
        /// СуммаЕжПлЗаКр.
        /// </summary>
        // *** Start programmer edit section *** (ПроверкаКрКл.СуммаЕжПлЗаКр CustomAttributes)

        // *** End programmer edit section *** (ПроверкаКрКл.СуммаЕжПлЗаКр CustomAttributes)
        public virtual int СуммаЕжПлЗаКр
        {
            get
            {
                // *** Start programmer edit section *** (ПроверкаКрКл.СуммаЕжПлЗаКр Get start)

                // *** End programmer edit section *** (ПроверкаКрКл.СуммаЕжПлЗаКр Get start)
                int result = this.fСуммаЕжПлЗаКр;
                // *** Start programmer edit section *** (ПроверкаКрКл.СуммаЕжПлЗаКр Get end)

                // *** End programmer edit section *** (ПроверкаКрКл.СуммаЕжПлЗаКр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПроверкаКрКл.СуммаЕжПлЗаКр Set start)

                // *** End programmer edit section *** (ПроверкаКрКл.СуммаЕжПлЗаКр Set start)
                this.fСуммаЕжПлЗаКр = value;
                // *** Start programmer edit section *** (ПроверкаКрКл.СуммаЕжПлЗаКр Set end)

                // *** End programmer edit section *** (ПроверкаКрКл.СуммаЕжПлЗаКр Set end)
            }
        }
        
        /// <summary>
        /// Проверка кр кл.
        /// </summary>
        // *** Start programmer edit section *** (ПроверкаКрКл.ЗаклКрДог CustomAttributes)

        // *** End programmer edit section *** (ПроверкаКрКл.ЗаклКрДог CustomAttributes)
        [PropertyStorage(new string[] {
                "ЗаклКрДог"})]
        [NotNull()]
        public virtual IIS.Otdel.ЗаклКрДог ЗаклКрДог
        {
            get
            {
                // *** Start programmer edit section *** (ПроверкаКрКл.ЗаклКрДог Get start)

                // *** End programmer edit section *** (ПроверкаКрКл.ЗаклКрДог Get start)
                IIS.Otdel.ЗаклКрДог result = this.fЗаклКрДог;
                // *** Start programmer edit section *** (ПроверкаКрКл.ЗаклКрДог Get end)

                // *** End programmer edit section *** (ПроверкаКрКл.ЗаклКрДог Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПроверкаКрКл.ЗаклКрДог Set start)

                // *** End programmer edit section *** (ПроверкаКрКл.ЗаклКрДог Set start)
                this.fЗаклКрДог = value;
                // *** Start programmer edit section *** (ПроверкаКрКл.ЗаклКрДог Set end)

                // *** End programmer edit section *** (ПроверкаКрКл.ЗаклКрДог Set end)
            }
        }
        
        /// <summary>
        /// Проверка кр кл.
        /// </summary>
        // *** Start programmer edit section *** (ПроверкаКрКл.Организация CustomAttributes)

        // *** End programmer edit section *** (ПроверкаКрКл.Организация CustomAttributes)
        [PropertyStorage(new string[] {
                "Организация"})]
        [NotNull()]
        public virtual IIS.Otdel.Организация Организация
        {
            get
            {
                // *** Start programmer edit section *** (ПроверкаКрКл.Организация Get start)

                // *** End programmer edit section *** (ПроверкаКрКл.Организация Get start)
                IIS.Otdel.Организация result = this.fОрганизация;
                // *** Start programmer edit section *** (ПроверкаКрКл.Организация Get end)

                // *** End programmer edit section *** (ПроверкаКрКл.Организация Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПроверкаКрКл.Организация Set start)

                // *** End programmer edit section *** (ПроверкаКрКл.Организация Set start)
                this.fОрганизация = value;
                // *** Start programmer edit section *** (ПроверкаКрКл.Организация Set end)

                // *** End programmer edit section *** (ПроверкаКрКл.Организация Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПроверкаКрКлE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПроверкаКрКлE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПроверкаКрКлE", typeof(IIS.Otdel.ПроверкаКрКл));
                }
            }
            
            /// <summary>
            /// "ПроверкаКрКлL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПроверкаКрКлL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПроверкаКрКлL", typeof(IIS.Otdel.ПроверкаКрКл));
                }
            }
        }
    }
}
